###############################################
# Common Keys
###############################################
x-common-keys: &common-keys
  restart: unless-stopped
  logging:
    driver: json-file
  environment:
    PUID: 1000
    PGID: 1000
    TZ: Europe/Amsterdam
  dns:
    - 192.168.1.17
    - 1.1.1.1

services:

###############################################
# VPN (Gluetun)
###############################################
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=gMlMHrZZm8+InM6DGNXRzUJrI6o0XAa4Y39G6gaWX0o=
      - WIREGUARD_ADDRESSES=192.168.1.16/32
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL_VPN_INPUT_PORTS=8080,6881
    ports:
      - 9696:9696 #prowlarr
      - 7878:7878 #radarr
      - 8989:8989 #sonarr
      - 6767:6767 #bazarr
      - 8686:8686 #lidarr
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent

###############################################
# RADARR
###############################################
  radarr:
    <<: *common-keys
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
    networks:
      - arr_network

###############################################
# SONARR
###############################################
  sonarr:
    <<: *common-keys
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
    networks:
      - arr_network

###############################################
# LIDARR
###############################################
  lidarr:
    <<: *common-keys
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
      - 8686:8686
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /data:/data
    networks:
      - arr_network

###############################################
# BAZARR
###############################################
  bazarr:
    <<: *common-keys
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    networks:
      - arr_network

###############################################
# PROWLARR
###############################################
  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
    networks:
      - arr_network

###############################################
# QBITTORRENT (via VPN)
###############################################
  qbittorrent:
    <<: *common-keys
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /data:/data

###############################################
# PLEX
###############################################
  plex:
    <<: *common-keys
    container_name: plex
    image: ghcr.io/hotio/plex:latest
    ports:
      - 32400:32400
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/plex:/config
      - /data/media:/data/media:ro
    networks:
      - arr_network

###############################################
# NETWORK
###############################################
networks:
  arr_network:
    name: arr_network
